// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import SmileOutlined from '/Users/tjh/works/pip/node_modules/@ant-design/icons/es/icons/SmileOutlined';
import BarChartOutlined from '/Users/tjh/works/pip/node_modules/@ant-design/icons/es/icons/BarChartOutlined';
import ContactsOutlined from '/Users/tjh/works/pip/node_modules/@ant-design/icons/es/icons/ContactsOutlined';
export default { SmileOutlined, BarChartOutlined, ContactsOutlined };
