// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import React from 'react';

export async function getRoutes() {
  const routes = {"1":{"path":"/user","layout":false,"id":"1"},"2":{"name":"login","path":"/user/login","parentId":"1","id":"2"},"3":{"path":"/dashBoard","name":"dashBoard","icon":"smile","parentId":"ant-design-pro-layout","id":"3"},"4":{"name":"dataShow","icon":"barChart","path":"/dataShow","parentId":"ant-design-pro-layout","id":"4"},"5":{"path":"/dataShow/multidata","name":"multidata","parentId":"4","id":"5"},"6":{"name":"customer","icon":"contacts","path":"/customer","parentId":"ant-design-pro-layout","id":"6"},"7":{"path":"/customer/information","name":"information","parentId":"6","id":"7"},"8":{"path":"/customer/information/moreInfo","parentId":"6","id":"8"},"9":{"path":"/","redirect":"/dashBoard","parentId":"ant-design-pro-layout","id":"9"},"10":{"path":"*","layout":false,"id":"10"},"ant-design-pro-layout":{"id":"ant-design-pro-layout","path":"/","isLayout":true}} as const;
  return {
    routes,
    routeComponents: {
'1': React.lazy(() => import( './EmptyRoute')),
'2': React.lazy(() => import(/* webpackChunkName: "p__User__Login__index" */'@/pages/User/Login/index.tsx')),
'3': React.lazy(() => import(/* webpackChunkName: "p__DashBoard__index" */'@/pages/DashBoard/index.tsx')),
'4': React.lazy(() => import( './EmptyRoute')),
'5': React.lazy(() => import(/* webpackChunkName: "p__DataShow__Multidata__index" */'@/pages/DataShow/Multidata/index.tsx')),
'6': React.lazy(() => import( './EmptyRoute')),
'7': React.lazy(() => import(/* webpackChunkName: "p__Customer__Information__index" */'@/pages/Customer/Information/index.tsx')),
'8': React.lazy(() => import(/* webpackChunkName: "p__Customer__Information__MoreInfo__index" */'@/pages/Customer/Information/MoreInfo/index.tsx')),
'9': React.lazy(() => import( './EmptyRoute')),
'10': React.lazy(() => import(/* webpackChunkName: "p__404" */'@/pages/404.tsx')),
'ant-design-pro-layout': React.lazy(() => import(/* webpackChunkName: "t__plugin-layout__Layout" */'/Users/tjh/PIP/src/.umi-production/plugin-layout/Layout.tsx')),
},
  };
}
